title: Hyomin Han
logo: /assets/img/hyomin-torso.jpeg
email: 
description: 
show_downloads: false
google_analytics: 
# theme: jekyll-theme-minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

remote_theme: BDHU/minimalist